### ISSUE TITLE
Deploy chef-file on supermarket.chef.io (optionally rename it)

### ISSUE THREAD

**Issue by maoo** [jenssegers/chef-patch#10]
I've recently published my artifact-deployer cookbook on supermarket.chef.io, but since it depends on chef-file, it cannot be entirely resolved on supermarket, forcing to define a `Berksfile` on each project that wants to use it.

Using [stove](http://sethvargo.github.io/stove/) it's very simple to setup a release process and publish on supermarket ([artifact-deployer uses it](https://github.com/maoo/artifact-deployer/blob/master/RELEASE.md))

Not sure if the name "file" for the cookbook is too generic and/or misleading with the Chef `file` resource; it would be worthwhile to change name before publishing.

Thanks!
  mao

**Comment by ramonskie** [comment]
@jenssegers any other suggestions 
or did you abandon this?

**Comment by jenssegers** [comment]
I did not abandon this, I just don't have experience with publishing on the supermarket yet :)

**Comment by maoo** [comment]
Found https://github.com/someara/line-cookbook on the supermarket, which seems to deliver very similar features.

**Comment by jenssegers** [comment]
Would be great if someone could help me getting this on supermarket though :)

**Comment by maoo** [comment]
This link should be all actually - https://supermarket.chef.io/become-a-contributor

In order to perform a release, check https://github.com/maoo/artifact-deployer/blob/master/RELEASE.md and https://github.com/sethvargo/stove

**Comment by jenssegers** [comment]
Anyone has a suggestion for a new name?

**Comment by jenssegers** [comment]
I would actually prefer to rename all the resources to `append_line`, `replace_line` etc. But I don't think this is possible with the current setup as the cookbook name is prepended before the included resources. Anyone has any input on this?

**Comment by maoo** [comment]
I think you should switch to the new custom resources introduced in Chef 12.5 - https://www.chef.io/blog/2015/10/08/chef-client-12-5-released/

You can follow the Chef webinar (Custom Resources in Chef 12.5)

As per the name, wdyt of `filepatch`? Supermarket doesnt have any entry with that name - https://supermarket.chef.io/cookbooks?utf8=%E2%9C%93&q=filepatch&platforms%5B%5D=

As commented above, I'm not sure what's the added value of this cookbook, compared to https://github.com/someara/line-cookbook ; if there's none, why not just switching to use that one?

**Comment by jenssegers** [comment]
I think the biggest difference is that this cookbook is using `Chef::Util::FileEdit` to do the replace operations.

**Comment by jenssegers** [comment]
Updated the cookbook to use the new resources. But I can't figure out how to fix the tests though.

**Comment by jenssegers** [comment]
I managed to get an initial 3.0.0 version on the supermarket. Now all that's left is fixing the tests so that Travis stops complaining :)

**Comment by maoo** [comment]
Thanks @jenssegers ! I'll test the new version on my cookbooks

**Comment by ramonskie** [comment]
I will try to fix your tests tomorrow
