### ISSUE TITLE
insert_line_after does not work anymore since rename  from insert_line_after_match

### ISSUE THREAD

**Issue by ramonskie** [jenssegers/chef-patch#17]
i don't know why
but the insert_line_after does not work anymore since the rename from insert_line_after_match

**Comment by ramonskie** [comment]
found the issue
https://github.com/jenssegers/chef-patch/blob/master/resources/insert_line_after.rb#L32
should be 

```
file.insert_line_after_match(regex, insert)
```

i think to keep our sanity we need to rollback and just call it insert_line_after_match again
don't you agree?

**Comment by jenssegers** [comment]
`insert_line_after` is more similar to the other methods though. Can you make a PR to fix that line?

**Comment by ramonskie** [comment]
yes but wouldn't it be nicer to have the same nameing as fileedit issues 
http://www.rubydoc.info/gems/chef/Chef/Util/FileEdit

**Comment by ramonskie** [comment]
https://github.com/jenssegers/chef-patch/pull/18

**Comment by jenssegers** [comment]
Can you try updating?
